server:
  port: 12000

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.guodf.owner.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: basic_info
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cctcms              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间



logging:
  pattern:
    # %d（时间）%msg（打印信息）%n换行
    console: "%d - %msg%n"
  #日志输出路径（部署后可以指定部署路径)
  #日志输出到指定文件（部署后可以指定部署路径）
  level: debug
  #日志级别指定到某个类
  # com.zlt.LoggerTest: debug
  file:
    name: E:/log/11100.log
    path: E:/log/